image: node:slim

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - npm install

stages:
  - deploy
        
deploy_to_aws:
  only:
    - master
  stage: deploy
  script:
    - chmod +x deploy/disableHostKeyChecking.sh
    - chmod +x deploy/updateServer.sh
    - chmod +x deploy/deploy.sh
    - bash deploy/deploy.sh